// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package landing_page

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "nugu.dev/rd-vigor/views/layout"

func LandingIndex(title string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"py-4 px-8 flex items-center h-14 border-b border-solid border-gray-200\"><a class=\"h-8 w-8 flex items-center space-x-1 mr-3 sm:mr-6\"><img class=\"w-full\" src=\"static/img/logo.svg\"></a><div class=\"flex items-center space-x-3\"><a class=\"p-1 text-[#27272A] cursor-pointer\">Home</a> <a class=\"p-1 text-[#71717A] cursor-pointer\">Eventos</a> <a class=\"p-1 text-[#71717A] cursor-pointer\">Reuniões</a></div><div class=\"flex items-center ml-auto space-x-4\"><button class=\"text-sm px-4 py-2 rounded-full bg-[#27272A] text-white font-medium\"><span class=\"sm:block\">Login</span></button></div></div><div class=\"flex flex-col items-center justify-center grow\"><div class=\"card-shadow relative rounded-3xl h-96 w-3/5 border border-solid border-gray-200 flex flex-col\" style=\"background-image: linear-gradient(to right top, #ffdfa9, #fed18c, #fec371, #feb455, #fea439);\"><div class=\"flex card-shadow py-1 px-2 w-4/5 bg-white absolute -bottom-7 rounded-3xl left-1/2 -translate-x-1/2 border border-solid border-gray-200\"><div class=\" relative h-10 w-10\"><img class=\"w-full\" src=\"static/img/search.svg\"></div><input class=\"w-full flex-grow\" type=\"text\" placeholder=\"Procure por uma ocupação ou empresa especifica\"> <button class=\"ml-3\" type=\"button\">aaaaa</button></div></div></div><div class=\"py-4 px-8 flex justify-center border-t border-solid border-gray-200\"><span class=\"text-[#71717A]\">© RD Vigor 2024</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base(title).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
