// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package auth_views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SigninForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"flex flex-col space-y-3 w-full\"><input class=\"py-3 px-4 w-full font-normal rounded-md border border-gray-200 border-solid\" placeholder=\"E-mail\"> <input class=\"py-3 px-4 w-full font-normal rounded-md border border-gray-200 border-solid\" placeholder=\"Senha\"> <button hx-get=\"/not-ready\" hx-target=\"#form-box\" class=\"p-3 w-full text-lg font-semibold rounded-md text-white bg-[#FFBD59]\">Entrar</button></form><a class=\"text-sm text-[#FFBD59] cursor-pointer font-normal\">Esqueceu a senha?</a><hr class=\"w-full h-px bg-gray-200 border-0\"><button id=\"signup-button\" hx-get=\"/signup\" hx-target=\"#form-box\" class=\"p-3 w-full font-semibold text-lg rounded-md text-white bg-[#441a06]\">Criar nova conta</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func SigninFormDone() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col justify-between items-center w-full\"><div><h1 class=\"text-center text-gray-400 text-md\">Obrigado por se cadastrar na RD Vigor. No momento ainda estamos dando os últimos retoques na plataforma para que você tenha a melhor experiência possivel. Assim que tudo estiver pronto enviaremos um e-mail para você. Nos vemos em breve!</h1></div><a hx-get=\"/\" hx-target=\"body\" class=\"text-md mt-3 text-[#FFBD59] cursor-pointer font-normal\">Voltar</a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
